### ISSUE TITLE
Add docs about which versions of Rails no longer need this patch?

### ISSUE THREAD

**Issue by philipithomas** [anycable/action-cable-redis-backport#3]
I followed the patch PR, and it's hard to tell whether it made it into the 7.0 line of Rails. Do you have the exact patch version where it went out, or is it still pending a 7.1 release?

**Comment by palkan** [comment]
Yeah, it's still pending 7.1 🤷‍♂️

**Comment by marcoroth** [comment]
Rails 7.1 just released 🎉
